name: Portfolio-Bot
on: [push] # This triggers the bot every time you push code

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: WOOOOOOOOOOO I  DID IT
        run: echo "Bot is checking your new code... All looks good!"


